name: Check

on:
  push:
  pull_request:

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: "1"
      - run: npm run check
